### ISSUE TITLE
confusing exercise

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/shell-genomics#126]
The exercise "How many bad reads are there in the two FASTQ files combined?" was confusing for learners. All started to extract bad reads from each fastq file. It might be clearer to phrase this as: "how many bad reads from the two FASTQ files are in scripted_bad_reads.txt"?

**Comment by donalbonny** [comment]
1. I agree. It would be great if we can change the question as aschuerch's comment. In addition, the bonus question: " How many bad reads are in each of the two FASTQ files ?" could be clearer if we can change to: how many bad reads from each of the two FASTQ files are in the scripted_bad_reads.txt. We already did counting the bad reads from each of the two FASTQ files in previous steps using the different commands. People might get confused about the same questions. 
2. Even though we already explained "cut" function previously. It would be nice to explain a little bit how it works here so that the learners can get the solution.  We can add something like " To cut using a delimiter use the cut -d option. This is normally used in conjunction with the -f option to specify the field that should be cut.

**Comment by ErinBecker** [comment]
The exercise language currently matches @aschuerch's suggestion above and the `cut` exercises have been moved to an [extra optional lesson](https://datacarpentry.org/shell-genomics/extras/Extra_lesson.html). Closing this issue. Thank you @aschuerch and @donalbonny!
