### ISSUE TITLE
Episode 01:  `cd` and `ls` introduction

### ISSUE THREAD

**Issue by bebatut** [datacarpentry/shell-genomics#142]
Hi,

In the first episode, several shell commands are introduced: `pwd`, `cd` and `ls`.

I found it quite confusing how `cd` and `ls` are introduced.
First, it is written: "Let's look at how our file system is organized.", but we have no way (except `ls`) to look at the structure (because of no GUI).
Then, the directories are given as the result of a command (which is not indicated). And the learners needs to move with `cd` and at the end `ls` is explained.

See screenshot:
![screen shot 2018-05-18 at 16 54 25](https://user-images.githubusercontent.com/1842467/40241844-4d92fb32-5abc-11e8-9119-380e6d410e6d.png)

Do you think it would not make sense to first introduce `ls` right after the "Let's look at how our file system is organized." and then `cd`?

Bérénice

**Comment by jrkirk61** [comment]
Like @aschuerch, I usually start with a visual aid that shows all the directories and sub-directories in relation to one another. However, like @bebatut, I also find it anti-intuitive to introduce 'cd' first. I'd want to use 'ls' before and after they try the 'cd' command so they can see exactly what it did. For those who've never used the Linux CLI, the biggest hurdle for them is being able to conceptualize or visualize the directory structure in their minds because they no longer have a GUI to fall back on. I find that 'ls' helps reinforce the directory structure concept, so I use it before and after almost every command to show students what changed, and so I introduce it as early as possible. 

I also believe when I taught this lesson a few months ago, I moved it around during the live coding, so that 'ls' came first. So, in short, I agree that 'ls' should come before 'cd'.

**Comment by mfoos** [comment]
I've never taught this lesson and it's been years since I helper'd it, but I rarely run `pwd` without `ls` either before or after, so I would probably have run `ls` and gone "Whoops" and explained it before I ever got to the "Let's look at how our file system is organized." part.

**Comment by ErinBecker** [comment]
I also found the use of `pwd` and `cd` before `ls` disorienting and confusing. I'd be happy to put in a PR to reorganize that section, if that would be helpful. Please let me know @aschuerch if you'd like me to go ahead and give it a try!

**Comment by aschuerch** [comment]
Please go ahead @ErinBecker!

**Comment by aschuerch** [comment]
See also #202

**Comment by ErinBecker** [comment]
Thanks @aschuerch for the go ahead. I've assigned this to myself and will put in a PR within the next week.

**Comment by ErinBecker** [comment]
Working on this now!
