### ISSUE TITLE
stylesheet missing for Episode - Extra - File manipulation

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/shell-genomics#190]
See also #177

**Comment by ErinBecker** [comment]
@aschuerch - I think the issue is that files in `_extras` can't use the episode YAML header format (which includes timing information, questions, objectives, and keypoints). I've put in a PR (#193) which changes the YAML header to be the default "page" layout. This should preserve all styling and information *except* the following: 

teaching: 10
exercises: 10
questions:
- "How can I work with tables on the command line?"
objectives:
- "Manipulate tabular files on the command line."
keypoints:
- "`cut`, `sort` and `uniq` are powerful tools to manipulate files."
- "`command_1 | command_2` redirects the output of the first command as input to the second command."

If the preference is to preserve this information, we can move this extra episode to the `_episodes` folder and mark it as optional in the name.

**Comment by aschuerch** [comment]
Thank you, it's fine like this!

**Comment by ErinBecker** [comment]
Great, thanks for merging @aschuerch!
