### ISSUE TITLE
Extra exercise in 'redirection'

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/shell-genomics#194]
With the move of 'File manipulation' to Extra, there is a single mention of the Pipe ('|')  in https://datacarpentry.org/shell-genomics/04-redirection/ 
I think we should add another example and introduce an exercise at the end of 'Redirecting output', before 'Loops,' to apply what has been learnt in this section.

**Comment by erinroberts** [comment]
I'd like to tackle this as part of finishing my data carpentry instructor certification. Are there specific examples you think might be most beneficial? A command I often use is grep "string" filename.fastq | wc -l . Because wc -l was introduced right before this, I think this pipe would be an obvious addition. Then at the end of the section for an exercise we could ask "Find lines and headers with this sequence GATCGTC, extract the quality score, and redirect the output for a new file". They could do grep -B1 -A2 "GATCGTC" | cut -f2 > read quality.txt. Thanks

**Comment by aschuerch** [comment]
Hi Erin, thank you for picking this up! The example you have in mind makes sense to me. However, the exercise is a bit problematic, as cut was not introduced yet at this stage. This exercise also introduces the concept of stacking the redirects, so maybe we should keep the rest simple. How about changing that to e.g. "Find read with the sequence "GATCGTC", count them and redirect it to a new file?" Which would be grep "GATCGTC" | wc -l > reads_with_pattern.txt
What do you think? I pull request would be highly appreciated.

**Comment by erinroberts** [comment]
Sorry for the delay on this, I just finished adding in the second example. Working on the exercise now. I like your suggestion, but the contents of the file made through the redirect would just be the numerical count of the number of lines that have been found with grep. How about an exercise where we ask to find a specific sequence and grab the quality score line, extract sequences that are 35 base pairs in length, and then pipe output to a file, `grep -B1 "GATCGTC" SRR098026.fastq | grep -A1 "length=35" > sequences_35bp.txt `. This is a little complicated, but it uses tools they should have already gained in the lesson and seeing that the length is expressly given in the fastq header. What do you think?

**Comment by akshayparopkari** [comment]
Closing this issue.

As per @aschuerch's [comment](https://github.com/datacarpentry/shell-genomics/pull/258#issuecomment-536901120), #258 fixed this issue.
