### ISSUE TITLE
Instructors note 404

### ISSUE THREAD

**Issue by EstherPlomp** [datacarpentry/shell-genomics#199]
The instructor's notes for the "Introduction to the Command Line for Genomics" are unavailable: https://datacarpentry.org/shell-genomics/guide/

**Comment by aschuerch** [comment]
Thank you for reporting!

**Comment by ErinBecker** [comment]
Thank you @EstherPlomp for reporting the issue. After a bit of troubleshooting, I've found that the link from the lessons page and the link from within the lesson itself are different.

From the overall DC lessons page the link is https://datacarpentry.org/shell-genomics/guide/ (which 404s)
From within the Extras menu in the lesson itself, the link is https://datacarpentry.org/shell-genomics/extras/guide (which works).

I've put in a PR to the Data Carpentry website repo (https://github.com/datacarpentry/datacarpentry.github.io/pull/479) for a quick fix. However, other lessons' instructor notes use the `lesson/guide/` syntax rather than the `lesson/extras/guide` syntax. Hoping that @fmichonneau can advise about where the problem lies. Let's leave this open until we can make sure this isn't a deeper problem with the template.

**Comment by aschuerch** [comment]
This was not fixed for me with #217 . The guide is at https://datacarpentry.org/shell-genomics/guide/index.html but the link on the main page goes to https://datacarpentry.org/guide/index.html -> 404

**Comment by aschuerch** [comment]
This was not fixed by pull request #217

**Comment by fmichonneau** [comment]
I think I had misunderstood this. Was the issue the link in the datacarpentry.org/lesson page? If so, I now updated it to point it to the correct path. Feel free to re-open if I got it wrong!

**Comment by aschuerch** [comment]
Does not fix it for me. On the main page https://datacarpentry.org/shell-genomics/, under the header "*For instructors", the link points to https://datacarpentry.org/guide/index.html but the instructor notes are at https://datacarpentry.org/shell-genomics/guide/index.html
