### ISSUE TITLE
Updating Learning Objectives

### ISSUE THREAD

**Issue by kariljordan** [datacarpentry/shell-genomics#22]
Hi @mckays630 and @kcranston,

I sent an e-mail on December 19th regarding updating the learning objectives for the command line and data wrangling lessons. The proposed learning objectives are attached. I'd appreciate your feedback on these revised learning objectives, and once you've approved then I'll submit a pull request to update the lesson.

Data Carpentry is in the process of revising the learning objectives for all of our lessons such that they are measurable.

Thank you for your help and time. The files are attached.

Kari
[Data-wrangling-and-processing-LOsharedwithmaintainers.docx](https://github.com/datacarpentry/shell-genomics/files/685438/Data-wrangling-and-processing-LOsharedwithmaintainers.docx)
[Introduction-to-the-command-line-LOsharedwithmaintainers.docx](https://github.com/datacarpentry/shell-genomics/files/685439/Introduction-to-the-command-line-LOsharedwithmaintainers.docx)

**Comment by kcranston** [comment]
Hi Kari,
Thanks for your efforts to improve these lessons! Apologies for the late
reply. It would be simpler to make the changes and submit the PR, and then
we can review / discuss via the GitHub interface (rather than reviewing
email attachments). Then, we also have the history of changes and comments.
Based on a quick review of the files, I don't see anything controversial.

Cheers,
Karen

**Comment by kariljordan** [comment]
Hi @kcranston, great! I'll submit the PR.

**Comment by ErinBecker** [comment]
@kariljordan - is it ok to close this?

**Comment by kariljordan** [comment]
@ErinBecker absolutely
