### ISSUE TITLE
Lesson Contribution - Christina Straub

### ISSUE THREAD

**Issue by sheraaronhurt** [datacarpentry/shell-genomics#255]
having taught the intro to shell from the genomics data carpentry workshop recently, I have a comment to https://datacarpentry.org/shell-genomics/01-introduction/index.html :

Preparation Magic

If you type the command: PS1='$ ' into your shell, followed by pressing the Enter key, your window should look like our example in this lesson.
This isn't necessary to follow along (in fact, your prompt may have other helpful information you want to know about). This is up to you!

I know its great to know how to change the prompt, but is this really something that should be introduced so early on? And if it is introduced, students always wonder how do you get the original prompt back.

The solution is easy, by just logging out, but if you are working on a computing cluster, and have to deal with 2-factor authentication that's not really something that you would want everyone in the class to do.

My suggestion is to either remove this part of the lesson, or put in the command to restore it back to its default, which would usually something like

PS1="\u@\h:\w $ "

**Comment by aschuerch** [comment]
Hi Christina, thank you for raising this issue! I agree with you that this is problematic at the beginning of the lesson. However, I am against removing it, because some instructors (like me) need this to make enough space on the command line to teach sensibly, and feel it would be wrong to do this with some 'magic'. What I usually do is to tell the participants what I am doing, and why, but ask them not to follow along yet because the prompt contains a lot of info. But I also experienced that it still can be confusing to participants so early on. 

I like your suggestion of putting the command there to restore. A pull request would be appreciated!

**Comment by mjenica11** [comment]
Hello,
I thought adding an explanation about how to change the prompt back to the original value was a good idea.
I added a section explaining here: [https://github.com/datacarpentry/shell-genomics/pull/295](url)
I tried to be as explicit as possible, but consequently it's a bit long.

**Comment by mjenica11** [comment]
Hello,
I liked Christina's suggestion to add an explanation on how to change their shell prompt back to the original value, which I attempted here:
#https://github.com/datacarpentry/shell-genomics/pull/295
I aimed to be as explicit as possible and avoid jargon, but it's a bit challeniging because the original prompt may be different for each user.
