### ISSUE TITLE
issue for instructor checkout - submitted by email

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/shell-genomics#259]
my name is Mitsis Athanasios. I am a Ph.D. candidate at the Agricultural University of Athens and I d like to report an issue in Data Carpentry as part of my checkout procedure.

I have found a wording issue in the Introduction to the Command Line for Genomics lesson, specifically in the Navigating Files and Directories setup.

When describing the differences between full and relative paths, the text is as follows:

You can usually use either a full path or a relative path depending on what is most convenient. If we are in the home directory, it is more convenient to enter the relative path since it involves less typing.

The wording is somewhat unclear. What the authors seem to imply is:

If we are in the home directory (and all your work/tools/etc is there), it is more convenient to enter the relative path

but

if your work/tools/etc are scattered through your pc, the absolute path is more convenient to view our files.

Maybe using

You can usually use either a full path or a relative path depending on what is most convenient. If we are in the working directory, it is more convenient to enter the relative path since it involves less typing.

is a better option

If further information is required please feel free to communicate through this e-mail address (mitsis.ath91@gmail.com).

**Comment by akshayparopkari** [comment]
The current sentence structure does seem confusing, as being in home directory implies you will end up entering the full path to file/executable/etc. Following Mitsis' recommendation, it will be useful to provide readers with information for using full and relative paths when they are either in `/home/` or working directory.

Current sentence - 
You can usually use either a full path or a relative path depending on what is most convenient. If we are in the home directory, it is more convenient to enter the relative path since it involves less typing.

I agree with Mitsis' suggestion and would like to add to his sentence as following - 
You can usually use either a full path or a relative path depending on what is most convenient. If we are in the home directory, it is more convenient to enter the full path. If we are in the working directory, it is more convenient to enter the relative path since it involves less typing.

What do others think about the updated version?

**Comment by aschuerch** [comment]
@akshayparopkari great clarification!

**Comment by aschuerch** [comment]
I will close this issue. Feel free to re-open if necessary!
