### ISSUE TITLE
Project Organization - Navigating in Nano

### ISSUE THREAD

**Issue by waydeveldman** [datacarpentry/shell-genomics#270]
On my computer the keyboard shortcut Alt+Space in Nano brings up window options Minimize, Maximize, Move, etc, instead of navigating one word backward like the lesson says it's supposed to do.
Perhaps changing the "move forward one word " and "move back one word" shortcuts to Ctrl+→ and Ctrl+← would better? These shortcuts work on my computer, unlike Alt+Space.
Perhaps the Ctrl+arrows would be easier to remember also?

**Comment by akshayparopkari** [comment]
Hi @waydeveldman, thank you for raising this issue 👍

Similar to your experience, `Alt + Space` combination opens Spotlight - a search utility on my machine - instead of going back one word. After looking into nano's help text (`Ctrl + G`), I found this helpful direction -

`Control-key sequences are notated with a caret (^) symbol and can be entered either by using the Control (Ctrl) key or pressing the Escape (Esc) key twice.  Escape-key sequences are notated with the Meta (M-) symbol and can be entered using either the Esc, Alt, or Meta key depending on your keyboard setup.`

```
^Space                  Go forward one word
M-Space                 Go back one word
```

When I tried `Esc + Space` combination, the cursor went back one word, as expected. `Ctrl + arrows` might be specific to your machine, since using `Ctrl + -->` and `Ctrl + <--` didn't move the cursor on my machine.

---

Considering keyboard/machine specificity of nano shortcuts, it may be more beneficial to add use of alternative keys (i.e. `Esc` or `Alt`) for navigation. What do you think @datacarpentry/shell-genomics-maintainers?
