### ISSUE TITLE
Introducing the Shell - "man" command

### ISSUE THREAD

**Issue by waydeveldman** [datacarpentry/shell-genomics#271]
It is not explicitly said that the "man" command stands for manual. It is also not mentioned that the "man" command can be used in combination with commands other than "ls".

**Comment by akshayparopkari** [comment]
Hi @waydeveldman, thanks for raising this issue 👍 

Yes, you're right that `man` stands for manual and can be used with any other bash command aren't explicitly mentioned in the lesson. Though, its utility is _implicitly_ presented (e.g. `man grep` in [Redirection](https://datacarpentry.org/shell-genomics/04-redirection/index.html) and [Writing Scripts and Working with Data](https://datacarpentry.org/shell-genomics/05-writing-scripts/index.html)) which shows that `man` can be used in combination with other bash commands.

I think adding clarifying information (one/two sentences) about `man` is a good idea, especially since it encourages users to explore new bash commands and become familiar with reading their documentation. What do you think @datacarpentry/shell-genomics-maintainers?

**Comment by aschuerch** [comment]
I fully agree with @akshayparopkari  
Thanks for bringing it up @waydeveldman

**Comment by waydeveldman** [comment]
Yes, @akshayparopkari, you are right. Encouraging users to explore new/different bash commands with "man", or at least letting them know it is possible, is very important. Thank you.

**Comment by akshayparopkari** [comment]
I am posting @waydeveldman's response as a quote below. For some reason, it isn't showing up as a comment in this thread.

> Yes, @akshayparopkari, you are right. Encouraging users to explore new/different bash commands with "man", or at least letting them know it is possible, is very important. Thank you.

Thanks, @waydeveldman. Please feel free to initiate a pull request to resolve this issue. For step-by-step guide on contributing to Carpentries lesson content, please refer to [instructions for Carpentries lesson contribution](https://github.com/dmgt/swc_github_flow/blob/master/for_novice_contributors.md#instructions-for-contributing-to-the-carpentries-lesson-materials-using-graphical-or-command-line-interfaces-with-git-and-github).

**Comment by akshayparopkari** [comment]
fixed in #278
