### ISSUE TITLE
05-writing-scripts - use command line arguments

### ISSUE THREAD

**Issue by Coayala** [datacarpentry/shell-genomics#293]
Since most of the times a script is going to be used multiple times or to analyze different files in different directories, wouldn't it be worthy to teach the students how to create scripts with user defined arguments from the command line?

Instead of the current script in the lesson:

`grep -B1 -A2 -h NNNNNNNNNN *.fastq | grep -v '^--' > scripted_bad_reads.txt`

Maybe create a script that looks similar to:

````
filename=$1
grep -B1 -A2 -h NNNNNNNNNN $filename | grep -v '^--' > scripted_bad_reads.txt
````

It will be executed in the command line as  `$ bash bad-reads-script.sh *.fastq` so the explanation about the use of the wildcards will still be useful.

PS: In this lesson where it says "Be careful that you did not add the `$` at the beginning of the line." There is no `$` in the box mentioning the grep command so maybe that reminder is not needed.

**Comment by esallychang** [comment]
Hi @Coayala thank you very much for this suggestion! I love the idea of making this script more generalizable/reproducible by introducing the concept of variables and user-defined arguments (and I use these all the time in my day-to-day work). Because this change introduces concepts (input, variables) which are not already part of the lesson flow I think it will take more work than just adding this bit of code. I am open to tackling this addition by writing a small additional part of this Lesson that gives some more context to these concepts and why they are super useful. Leaving this issue open for now, and will tag you in any modifications I make so you can see what we've done. Feel free to submit your own version of this this contextual text as a new pull request in the meantime @Coayala -  I do agree that this could be a worthy thing to teach!

I am also leaving the your other suggested edit as-is for the moment - if it was mentioned by the original lesson writers I suspect is is something that accidentally came up while using this lesson.

**Comment by aschuerch** [comment]
Thank you @Coayala and @esallychang for tackling this! Given how full the lesson already is (it should be possible to teach in about 4 hours), I would suggest that this content finds a home in  https://datacarpentry.org/shell-genomics/Extra_lesson/ , along with other additional material for the DC shell-genomics lesson.

**Comment by esallychang** [comment]
Great idea, I will tackle this as an addition to the "Extras" lesson rather than the main Writing Scripts lesson, @aschuerch. Planning to work on this later today.

**Comment by esallychang** [comment]
Hi @Coayala, I made a pull request that adds a very similar example to the one you suggested on our "Extras" page via PR #302 . I think it is a nice stating point for building a few other user-input examples, so thanks for the suggestion! When one of the other maintainers for this lessons merges this pull request, this issue will be closed. Feel free to make additions to this example in the future via new PRs!
