### ISSUE TITLE
Inconsistent usage of PuTTY/Git Bash (for Windows users)

### ISSUE THREAD

**Issue by ac1513** [datacarpentry/shell-genomics#312]
I've noticed there are some inconsistencies in the instructions for Windows users across the course around the usage of GitBash/PuTTY.

On the setup page, Git Bash is now the first 'recommended' software and PuTTY is down as 'alternative' but then going through the course the Windows-specific steps are written for PuTTY (e.g. the PSCP section in 05-writing-scripts, & this is also an issue in the Cloud section of the genomics course but that's in a separate repository).

Obviously, one of the advantages of Git Bash is that they will mainly be able to follow the UNIX instructions but this doesn't seem to be explained anywhere and will lead to confusion when they try and follow the Windows specific steps if not covered by the instructors. 

I'm not sure where the maintainers stand r.e. the recommendations of Git Bash / PuTTY on this course. I personally prefer Git Bash but I feel that as long as the instructions are updated to avoid confusion the PuTTY specific instructions should stay for those that are required to use PuTTY.

**Comment by crazyhottommy** [comment]
This is Tommy and I am serving as the chair of the genomic curriculum advisor committee. The Committee met and discussed it.

PuTTY seems to be a good backup if Git Bash won't install, concern in this issue is that there is some back and forth for the instructions. For consistency, it is better to stick with Git Bash but PuTTY as extra instruction/alternative.

As @JasonJWilliamsNY  said, we are not suggesting any particular direction, we are just sharing our experience.

Thanks, all the maintainers for your hard work!

**Comment by martinosorb** [comment]
+1 to this issue. The problem still stands: section 05 talks about "the same suite of tools as the PuTTY program we have been using to connect", but this is wrong, as most people will have installed gitbash and will be confused by this statement. And as an instructor, I'm not a Windows user and don't know how to do that with git bash (does it have scp? if so that makes it easy).
