### ISSUE TITLE
hidden directory for exercise

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/shell-genomics#53]
The exercise in 02-the-filesystem has learners using a directory ".hidden". It's likely not necessary to have it be an actual hidden directory with the . in front of it, as it add cognitive overhead. 

This would involve an update of the instance, but could the directory instead just be a regular directory called "hidden"?

**Comment by standage** [comment]
Isn't the primary purpose of this directory to show that some files (those that start with `.`) don't show up by default?

**Comment by tracykteal** [comment]
Originally this exercise had a directory 'hidden' with multiple directories in that directory, and the idea was that learners would navigate around in the directories to find the file 'youfoundit.txt' and then to find another file 'anotherfile.txt' without changing directories. 

https://github.com/tracykteal/shell-genomics-edamame/blob/master/README.md

It seemed to work pretty well.

**Comment by tracykteal** [comment]
The original goal of this exercise was to give people practice navigating around the filesystem at the command line. 

How important do we think it is for learners to know about hidden files (eg .file)

**Comment by standage** [comment]
> Originally this exercise had a directory 'hidden' with multiple directories in that directory, and the idea was that learners would navigate around in the directories to find the file 'youfoundit.txt' and then to find another file 'anotherfile.txt' without changing directories.

Got it.

> How important do we think it is for learners to know about hidden files (eg .file)

It's easy enough to cover in my opinion, but whether or not it's something that a particular learner is ever going to have to worry about as a beginner is another question entirely! :-)

**Comment by tracykteal** [comment]
This idea would then move this exercise to the 'Navigating Practice' exercise instead of the one that's there and if we wanted to take out the hidden files concept, remove the one that's there.

I think knowing that hidden files exist is useful, but when I'm teaching this I usually find it a little awkward to explain, especially given that people don't run into it that often, or if they do, there's usually documentation about it, for instance in configuration.

**Comment by ErinBecker** [comment]
If we remove the exercise where learners find the hidden directory, then also need to change later code that uses .hidden as an example for navigation practice. The problematic text is in 02-the-filesystem and is: 

Now enter the following command:

>$ cd /home/dcuser/dc_sample_data/.hidden
This jumps forward multiple levels to the .hidden directory. Now go back to the home directory.

>$ cd
You can also navigate to the .hidden directory using:

>$ cd dc_sample_data/.hidden
These two commands have the same effect, they both take us to the .hidden directory. The first uses the absolute path, giving the full address from the home directory. The second uses a relative path, giving only the address from the working directory. A full path always starts with a /. A relative path does not.

**Comment by ErinBecker** [comment]
I'm in favor of keeping the hidden directory and search exercise. It worked well the two times I've taught the material and I've found that that concept comes up more quickly than you might expect when starting to work with command-line programs in bioinformatics. I'll also note that we use a hidden directory to store the "lite" version of the fastq data. I assume that this is at least in part because we don't want learners accidentally using this directory until we get to the wrangling lesson. Keeping this as a hidden directory also makes tab complete much easier to use in the early exercises. So since we make use of a hidden directory in the wrangling lessons and it has benefits to use that hidden directory, I'm in favor of keeping this introduction to the concept of hidden directories/files here. 

Could the Maintainers please weigh in on this and decide whether to close this or turn into a PR? @aschuerch @smcclatchy @swang8 @gedankenstuecke

**Comment by gedankenstuecke** [comment]
I'm in favor of keeping the `.hidden` parts too. While hidden directories might not be of immediate use for beginners the concept of hidden things in general is. It relatively quickly becomes of interest as so many bioinformatics tools want to be added to your `PATH` by editing your `~/.bashrc` and in my experience the hidden nature throws people off if they haven't encountered it before.

**Comment by aschuerch** [comment]
I second @gedankenstuecke, and also because of the dependency of the rest of the lesson I would not remove the exercise. Plus last time I taught this I experienced this as a very informative assessment of the levels of the learners. Given that @ErinBecker @gedankenstuecke and I seem to agree I will close this issue.
